import type { CachedRepoView } from "./repository-service"

function formatMarkdownDate(isoString: string): string {
  const date = new Date(isoString)
  return Number.isNaN(date.getTime()) ? isoString : date.toISOString().slice(0, 10)
}

export function generateComparisonMarkdown(repos: CachedRepoView[]): string {
  const lines: string[] = []
  const exportDate = formatMarkdownDate(new Date().toISOString())
  const repoNames = repos.map((r) => r.fullName)

  lines.push(`# Repository Comparison: ${repoNames.join(" vs ")}`)
  lines.push("")
  lines.push(`> Discofork comparison report — exported ${exportDate}`)
  lines.push("")

  // Per-repo summaries
  for (const view of repos) {
    lines.push(`## ${view.fullName}`)
    lines.push("")
    lines.push(`> Source: ${view.githubUrl}`)
    lines.push("")
    lines.push(view.upstreamSummary)
    lines.push("")
  }

  // Stats comparison table
  lines.push("## Stats")
  lines.push("")
  lines.push(`| Metric | ${repoNames.join(" | ")} |`)
  lines.push(`|--------|${repos.map(() => "--------").join("|")}|`)
  lines.push(`| Stars | ${repos.map((v) => v.stats.stars.toLocaleString()).join(" | ")} |`)
  lines.push(`| Forks | ${repos.map((v) => v.stats.forks.toLocaleString()).join(" | ")} |`)
  lines.push(`| Default branch | ${repos.map((v) => v.stats.defaultBranch).join(" | ")} |`)
  lines.push(`| Last pushed | ${repos.map((v) => v.stats.lastPushedAt).join(" | ")} |`)
  lines.push("")

  // Recommendations comparison table
  lines.push("## Recommendations")
  lines.push("")
  lines.push(`| Category | ${repoNames.join(" | ")} |`)
  lines.push(`|----------|${repos.map(() => "--------").join("|")}|`)
  lines.push(`| Best maintained | ${repos.map((v) => v.recommendations.bestMaintained).join(" | ")} |`)
  lines.push(`| Closest to upstream | ${repos.map((v) => v.recommendations.closestToUpstream).join(" | ")} |`)
  lines.push(`| Most feature-rich | ${repos.map((v) => v.recommendations.mostFeatureRich).join(" | ")} |`)
  lines.push(`| Most opinionated | ${repos.map((v) => v.recommendations.mostOpinionated).join(" | ")} |`)
  lines.push("")

  // Top 3 forks per repo
  lines.push("## Top Forks")
  lines.push("")

  for (const view of repos) {
    lines.push(`### ${view.fullName}`)
    lines.push("")

    const topForks = view.forks.slice(0, 3)

    if (topForks.length === 0) {
      lines.push("No fork data available.")
      lines.push("")
      continue
    }

    for (const fork of topForks) {
      lines.push(`#### ${fork.fullName}`)
      lines.push("")
      lines.push(`**Maintenance:** ${fork.maintenance} · **Change magnitude:** ${fork.changeMagnitude}`)
      lines.push("")
      lines.push(fork.summary)
      lines.push("")
      lines.push(`**Likely purpose:** ${fork.likelyPurpose}`)
      lines.push("")
      lines.push(`**Best for:** ${fork.bestFor}`)
      lines.push("")

      if (fork.additionalFeatures.length > 0) {
        lines.push("**Additional features:**")
        lines.push("")
        for (const feature of fork.additionalFeatures) {
          lines.push(`- ${feature}`)
        }
        lines.push("")
      }

      if (fork.missingFeatures.length > 0) {
        lines.push("**Missing features:**")
        lines.push("")
        for (const feature of fork.missingFeatures) {
          lines.push(`- ${feature}`)
        }
        lines.push("")
      }

      if (fork.strengths.length > 0) {
        lines.push("**Strengths:**")
        lines.push("")
        for (const strength of fork.strengths) {
          lines.push(`- ${strength}`)
        }
        lines.push("")
      }

      if (fork.risks.length > 0) {
        lines.push("**Risks:**")
        lines.push("")
        for (const risk of fork.risks) {
          lines.push(`- ${risk}`)
        }
        lines.push("")
      }

      lines.push("---")
      lines.push("")
    }
  }

  lines.push(`*Generated by Discofork · ${exportDate}*`)
  lines.push("")

  return lines.join("\n")
}

function downloadComparisonMarkdown(repos: CachedRepoView[]): void {
  const markdown = generateComparisonMarkdown(repos)
  const ownerParts = repos.map((r) => `${r.owner}-${r.repo}`)
  const filename = `${ownerParts.join("_")}-comparison.md`

  const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" })
  const url = URL.createObjectURL(blob)

  const link = document.createElement("a")
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

export function exportComparison(repos: CachedRepoView[]): void {
  if (repos.length < 2) return
  downloadComparisonMarkdown(repos)
}
